server:
  port: 9000

spring:
  profiles: peer2
  application:
        name: isc-center
        
#logging.path=/logs/center/
logging:
    path: D:\logs\center\
    
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}:@project.version@
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${config.slave:http://localhost:9000/eureka/}
